Connected, dumping recent logs for app api-csc-fft in org CSC / space SRP as Wenting@icsc.com.tw...

2018-05-11T14:43:21.18+0800 [APP/PROC/WEB/0]ERR [2018-05-11 06:43:21 +0000] [44] [INFO] Worker exiting (pid: 44)
2018-05-11T14:43:21.19+0800 [APP/PROC/WEB/0]ERR [2018-05-11 06:43:21 +0000] [88] [INFO] Worker exiting (pid: 88)
2018-05-11T14:43:21.19+0800 [APP/PROC/WEB/0]ERR [2018-05-11 06:43:21 +0000] [47] [INFO] Worker exiting (pid: 47)
2018-05-11T14:43:21.20+0800 [APP/PROC/WEB/0]ERR [2018-05-11 06:43:21 +0000] [46] [INFO] Worker exiting (pid: 46)
2018-05-11T14:43:21.21+0800 [APP/PROC/WEB/0]ERR [2018-05-11 06:43:21 +0000] [45] [INFO] Worker exiting (pid: 45)
2018-05-11T14:43:21.22+0800 [APP/PROC/WEB/0]ERR [2018-05-11 06:43:21 +0000] [77] [INFO] Worker exiting (pid: 77)
2018-05-11T14:43:21.24+0800 [APP/PROC/WEB/0]ERR [2018-05-11 06:43:21 +0000] [69] [INFO] Worker exiting (pid: 69)
2018-05-11T14:43:21.34+0800 [APP/PROC/WEB/0]ERR [2018-05-11 06:43:21 +0000] [87] [INFO] Worker exiting (pid: 87)
2018-05-11T14:43:21.43+0800 [APP/PROC/WEB/0]ERR [2018-05-11 06:43:21 +0000] [101] [INFO] Worker exiting (pid: 101)
2018-05-11T14:43:21.64+0800 [API/0]      OUT Updated app with guid bf8299a3-6414-4db6-ac30-e2f8d4be0e54 ({"state"=>"STARTED"})
2018-05-11T14:43:21.66+0800 [STG/0]      OUT Downloading python_buildpack_offline...
2018-05-11T14:43:21.67+0800 [STG/0]      OUT Downloaded python_buildpack_offline
2018-05-11T14:43:21.67+0800 [STG/0]      OUT Creating container
2018-05-11T14:43:21.78+0800 [APP/PROC/WEB/0]ERR [2018-05-11 06:43:21 +0000] [8] [INFO] Shutting down: Master
2018-05-11T14:43:21.81+0800 [APP/PROC/WEB/0]OUT Exit status 0
2018-05-11T14:43:21.82+0800 [CELL/0]     OUT Destroying container
2018-05-11T14:43:22.44+0800 [STG/0]      OUT Successfully created container
2018-05-11T14:43:22.44+0800 [STG/0]      OUT Downloading app package...
2018-05-11T14:43:22.94+0800 [CELL/0]     OUT Successfully destroyed container
2018-05-11T14:43:24.26+0800 [STG/0]      OUT Downloaded app package (60.5M)
2018-05-11T14:43:24.26+0800 [STG/0]      OUT Downloading build artifacts cache...
2018-05-11T14:43:34.07+0800 [STG/0]      OUT Downloaded build artifacts cache (167.2M)
2018-05-11T14:43:34.07+0800 [STG/0]      OUT Staging...
2018-05-11T14:43:34.31+0800 [STG/0]      OUT -------> Buildpack version 1.5.20
2018-05-11T14:43:35.54+0800 [STG/0]      OUT -----> Installing pip-pop (0.1.1)
2018-05-11T14:43:35.66+0800 [STG/0]      OUT Downloaded [file:///tmp/buildpacks/90e184cb1aef440b56ca580b9e08cd7a/dependencies/https___buildpacks.cloudfoundry.org_dependencies_manual-binaries_pip-pop_pip-pop-0.1.1-d410583a.tar.gz]
2018-05-11T14:43:36.72+0800 [STG/0]      OUT -----> Installing pipenv (4.0.1)
2018-05-11T14:43:36.86+0800 [STG/0]      OUT Downloaded [file:///tmp/buildpacks/90e184cb1aef440b56ca580b9e08cd7a/dependencies/https___buildpacks.cloudfoundry.org_dependencies_manual-binaries_pipenv_pipenv-4.0.1-148f753f.tar.gz]
2018-05-11T14:43:39.53+0800 [STG/0]      ERR Traceback (most recent call last):
2018-05-11T14:43:39.53+0800 [STG/0]      ERR   File "/tmp/app/.cloudfoundry/0/python/lib/python3.6/site-packages/pip-9.0.1-py3.6.egg/pip/_vendor/packaging/requirements.py", line 92, in __init__
2018-05-11T14:43:39.54+0800 [STG/0]      ERR     req = REQUIREMENT.parseString(requirement_string)
2018-05-11T14:43:39.54+0800 [STG/0]      ERR   File "/tmp/app/.cloudfoundry/0/python/lib/python3.6/site-packages/pip-9.0.1-py3.6.egg/pip/_vendor/pyparsing.py", line 1617, in parseString
2018-05-11T14:43:39.54+0800 [STG/0]      ERR     raise exc
2018-05-11T14:43:39.54+0800 [STG/0]      ERR   File "/tmp/app/.cloudfoundry/0/python/lib/python3.6/site-packages/pip-9.0.1-py3.6.egg/pip/_vendor/pyparsing.py", line 1607, in parseString
2018-05-11T14:43:39.54+0800 [STG/0]      ERR     loc, tokens = self._parse( instring, 0 )
2018-05-11T14:43:39.54+0800 [STG/0]      ERR   File "/tmp/app/.cloudfoundry/0/python/lib/python3.6/site-packages/pip-9.0.1-py3.6.egg/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
2018-05-11T14:43:39.54+0800 [STG/0]      ERR     loc,tokens = self.parseImpl( instring, preloc, doActions )
2018-05-11T14:43:39.54+0800 [STG/0]      ERR   File "/tmp/app/.cloudfoundry/0/python/lib/python3.6/site-packages/pip-9.0.1-py3.6.egg/pip/_vendor/pyparsing.py", line 3376, in parseImpl
2018-05-11T14:43:39.54+0800 [STG/0]      ERR     loc, exprtokens = e._parse( instring, loc, doActions )
2018-05-11T14:43:39.54+0800 [STG/0]      ERR   File "/tmp/app/.cloudfoundry/0/python/lib/python3.6/site-packages/pip-9.0.1-py3.6.egg/pip/_vendor/pyparsing.py", line 1383, in _parseNoCache
2018-05-11T14:43:39.54+0800 [STG/0]      ERR     loc,tokens = self.parseImpl( instring, preloc, doActions )
2018-05-11T14:43:39.54+0800 [STG/0]      ERR   File "/tmp/app/.cloudfoundry/0/python/lib/python3.6/site-packages/pip-9.0.1-py3.6.egg/pip/_vendor/pyparsing.py", line 3164, in parseImpl
2018-05-11T14:43:39.54+0800 [STG/0]      ERR     raise ParseException(instring, loc, self.errmsg, self)
2018-05-11T14:43:39.54+0800 [STG/0]      ERR pip._vendor.pyparsing.ParseException: Expected stringEnd (at char 13), (line:1, col:14)
2018-05-11T14:43:39.54+0800 [STG/0]      ERR During handling of the above exception, another exception occurred:
2018-05-11T14:43:39.54+0800 [STG/0]      ERR Traceback (most recent call last):
2018-05-11T14:43:39.54+0800 [STG/0]      ERR   File "/tmp/app/.cloudfoundry/0/python/lib/python3.6/site-packages/pip-9.0.1-py3.6.egg/pip/req/req_install.py", line 82, in __init__
2018-05-11T14:43:39.54+0800 [STG/0]      ERR     req = Requirement(req)
2018-05-11T14:43:39.54+0800 [STG/0]      ERR   File "/tmp/app/.cloudfoundry/0/python/lib/python3.6/site-packages/pip-9.0.1-py3.6.egg/pip/_vendor/packaging/requirements.py", line 96, in __init__
2018-05-11T14:43:39.54+0800 [STG/0]      ERR     requirement_string[e.loc:e.loc + 8]))
2018-05-11T14:43:39.54+0800 [STG/0]      ERR pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'PyWavele'"
2018-05-11T14:43:39.54+0800 [STG/0]      ERR During handling of the above exception, another exception occurred:
2018-05-11T14:43:39.54+0800 [STG/0]      ERR Traceback (most recent call last):
2018-05-11T14:43:39.54+0800 [STG/0]      ERR   File "/tmp/app/.cloudfoundry/0/bin/pip-diff", line 116, in <module>
2018-05-11T14:43:39.54+0800 [STG/0]      ERR     main()
2018-05-11T14:43:39.54+0800 [STG/0]      ERR   File "/tmp/app/.cloudfoundry/0/bin/pip-diff", line 112, in main
2018-05-11T14:43:39.54+0800 [STG/0]      ERR     diff(**kwargs)
2018-05-11T14:43:39.54+0800 [STG/0]      ERR   File "/tmp/app/.cloudfoundry/0/bin/pip-diff", line 85, in diff
2018-05-11T14:43:39.54+0800 [STG/0]      ERR     r2 = Requirements(r2)
2018-05-11T14:43:39.54+0800 [STG/0]      ERR   File "/tmp/app/.cloudfoundry/0/bin/pip-diff", line 29, in __init__
2018-05-11T14:43:39.54+0800 [STG/0]      ERR     self.load(reqfile)
2018-05-11T14:43:39.54+0800 [STG/0]      ERR   File "/tmp/app/.cloudfoundry/0/bin/pip-diff", line 39, in load
2018-05-11T14:43:39.55+0800 [STG/0]      ERR     for requirement in parse_requirements(reqfile, finder=finder, session=requests):
2018-05-11T14:43:39.55+0800 [STG/0]      ERR   File "/tmp/app/.cloudfoundry/0/python/lib/python3.6/site-packages/pip-9.0.1-py3.6.egg/pip/req/req_file.py", line 93, in parse_requirements
2018-05-11T14:43:39.55+0800 [STG/0]      ERR     for req in req_iter:
2018-05-11T14:43:39.55+0800 [STG/0]      ERR   File "/tmp/app/.cloudfoundry/0/python/lib/python3.6/site-packages/pip-9.0.1-py3.6.egg/pip/req/req_file.py", line 158, in process_line
2018-05-11T14:43:39.55+0800 [STG/0]      ERR     isolated=isolated, options=req_options, wheel_cache=wheel_cache
2018-05-11T14:43:39.55+0800 [STG/0]      ERR   File "/tmp/app/.cloudfoundry/0/python/lib/python3.6/site-packages/pip-9.0.1-py3.6.egg/pip/req/req_install.py", line 235, in from_line
2018-05-11T14:43:39.55+0800 [STG/0]      ERR     wheel_cache=wheel_cache, constraint=constraint)
2018-05-11T14:43:39.55+0800 [STG/0]      ERR   File "/tmp/app/.cloudfoundry/0/python/lib/python3.6/site-packages/pip-9.0.1-py3.6.egg/pip/req/req_install.py", line 91, in __init__
2018-05-11T14:43:39.55+0800 [STG/0]      ERR     "Invalid requirement: '%s'\n%s" % (req, add_msg))
2018-05-11T14:43:39.55+0800 [STG/0]      ERR pip.exceptions.InstallationError: Invalid requirement: 'configparser PyWavelets'
2018-05-11T14:43:39.55+0800 [STG/0]      ERR Traceback (most recent call last):
2018-05-11T14:43:39.55+0800 [STG/0]      ERR   File "/tmp/app/.cloudfoundry/0/python/lib/python3.6/site-packages/pip-9.0.1-py3.6.egg/pip/_vendor/packaging/requirements.py", line 92, in __init__
2018-05-11T14:43:39.55+0800 [STG/0]      ERR     req = REQUIREMENT.parseString(requirement_string)
2018-05-11T14:43:39.55+0800 [STG/0]      ERR   File "/tmp/app/.cloudfoundry/0/python/lib/python3.6/site-packages/pip-9.0.1-py3.6.egg/pip/_vendor/pyparsing.py", line 1617, in parseString
2018-05-11T14:43:39.55+0800 [STG/0]      ERR     raise exc
2018-05-11T14:43:39.55+0800 [STG/0]      ERR   File "/tmp/app/.cloudfoundry/0/python/lib/python3.6/site-packages/pip-9.0.1-py3.6.egg/pip/_vendor/pyparsing.py", line 1607, in parseString
2018-05-11T14:43:39.55+0800 [STG/0]      ERR     loc, tokens = self._parse( instring, 0 )
2018-05-11T14:43:39.55+0800 [STG/0]      ERR   File "/tmp/app/.cloudfoundry/0/python/lib/python3.6/site-packages/pip-9.0.1-py3.6.egg/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
2018-05-11T14:43:39.55+0800 [STG/0]      ERR     loc,tokens = self.parseImpl( instring, preloc, doActions )
2018-05-11T14:43:39.55+0800 [STG/0]      ERR   File "/tmp/app/.cloudfoundry/0/python/lib/python3.6/site-packages/pip-9.0.1-py3.6.egg/pip/_vendor/pyparsing.py", line 3376, in parseImpl
2018-05-11T14:43:39.55+0800 [STG/0]      ERR     loc, exprtokens = e._parse( instring, loc, doActions )
2018-05-11T14:43:39.55+0800 [STG/0]      ERR   File "/tmp/app/.cloudfoundry/0/python/lib/python3.6/site-packages/pip-9.0.1-py3.6.egg/pip/_vendor/pyparsing.py", line 1383, in _parseNoCache
2018-05-11T14:43:39.55+0800 [STG/0]      ERR     loc,tokens = self.parseImpl( instring, preloc, doActions )
2018-05-11T14:43:39.55+0800 [STG/0]      ERR   File "/tmp/app/.cloudfoundry/0/python/lib/python3.6/site-packages/pip-9.0.1-py3.6.egg/pip/_vendor/pyparsing.py", line 3164, in parseImpl
2018-05-11T14:43:39.55+0800 [STG/0]      ERR     raise ParseException(instring, loc, self.errmsg, self)
2018-05-11T14:43:39.55+0800 [STG/0]      ERR pip._vendor.pyparsing.ParseException: Expected stringEnd (at char 13), (line:1, col:14)
2018-05-11T14:43:39.55+0800 [STG/0]      ERR During handling of the above exception, another exception occurred:
2018-05-11T14:43:39.55+0800 [STG/0]      ERR Traceback (most recent call last):
2018-05-11T14:43:39.55+0800 [STG/0]      ERR   File "/tmp/app/.cloudfoundry/0/python/lib/python3.6/site-packages/pip-9.0.1-py3.6.egg/pip/req/req_install.py", line 82, in __init__
2018-05-11T14:43:39.55+0800 [STG/0]      ERR     req = Requirement(req)
2018-05-11T14:43:39.55+0800 [STG/0]      ERR   File "/tmp/app/.cloudfoundry/0/python/lib/python3.6/site-packages/pip-9.0.1-py3.6.egg/pip/_vendor/packaging/requirements.py", line 96, in __init__
2018-05-11T14:43:39.55+0800 [STG/0]      ERR     requirement_string[e.loc:e.loc + 8]))
2018-05-11T14:43:39.55+0800 [STG/0]      ERR pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'PyWavele'"
2018-05-11T14:43:39.59+0800 [STG/0]      ERR Failed to compile droplet
2018-05-11T14:43:39.59+0800 [STG/0]      OUT Exit status 223
2018-05-11T14:43:39.61+0800 [STG/0]      ERR Staging failed: Exited with status 223
2018-05-11T14:43:39.61+0800 [STG/0]      OUT Destroying container
2018-05-11T14:43:44.84+0800 [STG/0]      OUT Successfully destroyed container
